reload:
  description: Reload localtuya and reconnect to all devices.

set_dp:
  description: Change the value of a datapoint (DP)
  fields:
    device_id:
      description: Device ID of device to change datapoint value for
      example: 11100118278aab4de001
    dp:
      description: Datapoint index
      example: 1
    value:
      description: New value to set
      example: False

get_library_devices:
  description: Get list of all devices in the BildaSystem device library.

get_device_template:
  description: Get entity template for a device from the library by product_key.
  fields:
    product_key:
      description: Tuya product key to look up
      example: sgodozglgymucvq2

reload_library:
  description: Reload the device library from disk.
